# Generated by Django 3.2.21 on 2023-12-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oz_product', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
