# Generated by Django 3.2.21 on 2023-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oz_product', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='.product_images/'),
        ),
    ]
