# Generated by Django 3.2.21 on 2023-12-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oz_product', '0007_cartitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
